services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: propaganda_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      target: production

    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/propaganda_db
      - ML_SERVICE_URL=http://ml_service:8000

  ml_service:
    build: 
      context: ./ml_service
      target: production
    # If running on AWS with GPU support:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  postgres_data:
